# Generated by Django 5.0.7 on 2024-08-05 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_order_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='track_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('warning_threshold', models.PositiveIntegerField(default=10)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'menu_item')},
            },
        ),
    ]
