# Generated by Django 5.0.7 on 2024-08-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_menuitem_track_stock_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_phone',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
