# Generated by Django 5.0.7 on 2024-08-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_restaurant_email_restaurant_owner_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner_phone',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_phone',
            field=models.CharField(max_length=14),
        ),
    ]
