# Generated by Django 5.0.7 on 2024-08-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_staff_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpense',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff'),
        ),
    ]
